# Generated by Django 5.0.1 on 2024-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empleado_habilitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(default='core/img/Default_user.png', upload_to='core/img/'),
        ),
    ]
