# Generated by Django 5.0.1 on 2024-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_empleado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(default='core/img/Default_user.png', upload_to='core/img/'),
        ),
    ]
