# Generated by Django 5.0.4 on 2024-05-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categorias_subirproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subirproyecto',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
