# Generated by Django 5.0.4 on 2024-05-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_subirproyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subirproyecto',
            name='descripcion',
            field=models.CharField(max_length=3000),
        ),
    ]
