# Generated by Django 5.0.4 on 2024-05-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
